name: ml-spm
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - cuda
  - ninja
  - matplotlib
  - numpy
  - scipy
  - webdataset<=0.2.86
  - scikit-image
  - pip:
    - ppafm[opencl]