name: ml-spm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - matplotlib
  - numpy
  - scipy
  - webdataset
  - pip:
    - ppafm[opencl]