name: ml-spm
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cuda
  - matplotlib
  - numpy
  - scipy
  - webdataset
  - scikit-image
  - pip:
    - ppafm[opencl]