
name: CI on push
on: push

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ['3.10', '3.11'] # Add 3.12 when pytorch has a wheel
    
    steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install package
          run: |
              bash ./build.sh
              pip install -e .[dev]
              pip install pocl-binary-distribution  # Required for test that use ppafm opencl functionality

        - name: Lint with flake8
          run: flake8 .

        - name: Run pytest
          run: pytest

